### ISSUE TITLE
Our group is in shambles

### ISSUE THREAD

**Issue by thomas43** [ChaseLEngel/upgraded-winner#24]
WHAT IS UPGRADED_WINNER, I mean who does HE think he is? upgraded_wumpus exemplifies our goals of this project. What is an upgraded_winner, how does one get upgraded from the most prestigious status obtainable by the common man? The ONLY name that makes sense is upgraded_wumpus, we only know 1 wumpus, and there is DEFINITELY room for an upgrade. 'He who must not be named' deleted my (anonymous) issue. THIS REPO IS PURELY WRONG.

**Comment by ChaseLEngel** [comment]
upgraded_wumpus is a hack!
